print("2.1 Caracteres de escape, nueva línea y print")

print()
print("2.1.8 Caracteres de escape y nueva línea en Python")
print("Estoy practicando el uso de print en Python.")
print()
print("En este ejercicio estoy viendo cómo mostrar texto en pantalla.")
print()
print("2.1.9 Usando múltiples argumentos")
print("Estoy", "aprendiendo", "a", "usar", "print", "correctamente.")
print()
print("2.1.11 Argumentos de palabra clave", end=" ")
print("Mi nombre es", "Elsy", end=" ")
print("Cuevas de la Torre.")
print()
print("Cuestionario")
print("Estoy\nestudiando\nPython\npaso a paso.", end=" ")
print("Cada ejercicio me ayuda a entender mejor.")
