print("2.2 Literales en Python")

print()
print("2.2.1 Literales - los datos escritos directamente en el código")
print("Un literal es un valor que se escribe tal cual dentro del programa.")
print()
print("Ejemplos de literales:")
print("Cadena:", "Hola, Python")
print("Entero:", 256)
print()
print("2.2.2 Enteros")
print("Los enteros son números sin parte decimal.")
print("Ejemplos de enteros:")
print(14)
print(-9)
print(2500000)
print(2_500_000)
print()
print("Números octales")
print("0o145 en octal equivale a:")
print(0o145)
print()
print("Números hexadecimales")
print("0x1A3 en hexadecimal equivale a:")
print(0x1A3)
print()
print("2.2.3 Flotantes")
print("Los flotantes tienen parte decimal.")
print("Ejemplos:")
print(3.75)
print(-1.2)
print(8.0)
print(.25)
print(9.)
print()
print("Notación científica")
print("2.5E4 representa 2.5 x 10^4")
print(2.5E4)
print("Constante gravitacional aproximada:")
print(6.67430E-11)
print()
print("2.2.4 Cadenas")
print("Las cadenas se usan para trabajar con texto.")
print("Ejemplo:")
print("Estoy aprendiendo Python.")
print()
print("Uso de comillas dentro de cadenas:")
print("Mi serie favorita es \"Dark\".")
print()
print("Otra forma:")
print('Mi serie favorita es "Dark".')
print()
print("2.2.5 Valores booleanos")
print("True representa verdadero")
print("False representa falso")
print(True)
print(False)
print()
print("Comparaciones:")
print(True > False)
print(True < False)
print()
print("LAB")
print("\"Estoy\"")
print("\"\"practicando\"\"")
print("\"\"\"Python\"\"\"")
